// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect CcfCoreStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CcfCoreStatusIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: CcfCoreStatusIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CcfCoreStatusIntegrationTest: @Transactional;
    
}
