// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import org.junit.jupiter.api.Test;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect DirectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DirectionIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: DirectionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DirectionIntegrationTest: @Transactional;
    
    @Test
    public void DirectionIntegrationTest.testCountDirections() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomDirection(), "Data on demand for 'Direction' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Direction.countDirections();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'Direction' incorrectly reported there were no entries");
    }
    
    @Test
    public void DirectionIntegrationTest.testFindDirection() {
        com.collabnet.ccf.ccfmaster.server.domain.Direction obj = dod.getRandomDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Direction' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Direction' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Direction.findDirection(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'Direction' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'Direction' returned the incorrect identifier");
    }
    
    @Test
    public void DirectionIntegrationTest.testFindAllDirections() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomDirection(), "Data on demand for 'Direction' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Direction.countDirections();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'Direction', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Direction> result = com.collabnet.ccf.ccfmaster.server.domain.Direction.findAllDirections();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'Direction' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'Direction' failed to return any data");
    }
    
    @Test
    public void DirectionIntegrationTest.testFindDirectionEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomDirection(), "Data on demand for 'Direction' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Direction.countDirections();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Direction> result = com.collabnet.ccf.ccfmaster.server.domain.Direction.findDirectionEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'Direction' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'Direction' returned an incorrect number of entries");
    }
    
    @Test
    public void DirectionIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.Direction obj = dod.getRandomDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Direction' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Direction' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Direction.findDirection(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'Direction' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyDirection(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'Direction' failed to increment on flush directive");
    }
    
    @Test
    public void DirectionIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.Direction obj = dod.getRandomDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Direction' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Direction' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Direction.findDirection(id);
        boolean modified =  dod.modifyDirection(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.Direction merged = (com.collabnet.ccf.ccfmaster.server.domain.Direction) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'Direction' failed to increment on merge and flush directive");
    }
    
    @Test
    public void DirectionIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.Direction obj = dod.getRandomDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Direction' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Direction' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Direction.findDirection(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.Direction.findDirection(id), "Failed to remove 'Direction' with identifier '" + id + "'");
    }
    
}
