// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.ExternalAppDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect ExternalAppIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExternalAppIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: ExternalAppIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ExternalAppIntegrationTest: @Transactional;
    
    @Autowired
    private ExternalAppDataOnDemand ExternalAppIntegrationTest.dod;
    
    @Test
    public void ExternalAppIntegrationTest.testCountExternalApps() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomExternalApp(), "Data on demand for 'ExternalApp' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.countExternalApps();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'ExternalApp' incorrectly reported there were no entries");
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFindExternalApp() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ExternalApp' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ExternalApp' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'ExternalApp' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'ExternalApp' returned the incorrect identifier");
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFindAllExternalApps() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomExternalApp(), "Data on demand for 'ExternalApp' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.countExternalApps();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'ExternalApp', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ExternalApp> result = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findAllExternalApps();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'ExternalApp' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'ExternalApp' failed to return any data");
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFindExternalAppEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomExternalApp(), "Data on demand for 'ExternalApp' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.countExternalApps();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ExternalApp> result = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalAppEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'ExternalApp' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'ExternalApp' returned an incorrect number of entries");
    }
    
    @Test
    public void ExternalAppIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ExternalApp' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ExternalApp' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'ExternalApp' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyExternalApp(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'ExternalApp' failed to increment on flush directive");
    }
    
    @Test
    public void ExternalAppIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ExternalApp' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ExternalApp' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        boolean modified =  dod.modifyExternalApp(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp merged = (com.collabnet.ccf.ccfmaster.server.domain.ExternalApp) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'ExternalApp' failed to increment on merge and flush directive");
    }
    
    @Test
    public void ExternalAppIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomExternalApp(), "Data on demand for 'ExternalApp' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getNewTransientExternalApp(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ExternalApp' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'ExternalApp' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'ExternalApp' identifier to no longer be null");
    }
    
    @Test
    public void ExternalAppIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.ExternalApp obj = dod.getRandomExternalApp();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ExternalApp' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ExternalApp' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.ExternalApp.findExternalApp(id), "Failed to remove 'ExternalApp' with identifier '" + id + "'");
    }
    
}
