// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRuleDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect FieldMappingRuleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldMappingRuleIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: FieldMappingRuleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FieldMappingRuleIntegrationTest: @Transactional;
    
    @Autowired
    private FieldMappingRuleDataOnDemand FieldMappingRuleIntegrationTest.dod;
    
    @Test
    public void FieldMappingRuleIntegrationTest.testCountFieldMappingRules() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingRule(), "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.countFieldMappingRules();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'FieldMappingRule' incorrectly reported there were no entries");
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFindFieldMappingRule() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingRule' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'FieldMappingRule' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'FieldMappingRule' returned the incorrect identifier");
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFindAllFieldMappingRules() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingRule(), "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.countFieldMappingRules();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'FieldMappingRule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findAllFieldMappingRules();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'FieldMappingRule' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'FieldMappingRule' failed to return any data");
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFindFieldMappingRuleEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingRule(), "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.countFieldMappingRules();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRuleEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'FieldMappingRule' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'FieldMappingRule' returned an incorrect number of entries");
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingRule' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'FieldMappingRule' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyFieldMappingRule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'FieldMappingRule' failed to increment on flush directive");
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingRule' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        boolean modified =  dod.modifyFieldMappingRule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule merged = (com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'FieldMappingRule' failed to increment on merge and flush directive");
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingRule(), "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getNewTransientFieldMappingRule(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingRule' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'FieldMappingRule' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'FieldMappingRule' identifier to no longer be null");
    }
    
    @Test
    public void FieldMappingRuleIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule obj = dod.getRandomFieldMappingRule();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingRule' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingRule' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule.findFieldMappingRule(id), "Failed to remove 'FieldMappingRule' with identifier '" + id + "'");
    }
    
}
