// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntryDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect FieldMappingValueMapEntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldMappingValueMapEntryIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: FieldMappingValueMapEntryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FieldMappingValueMapEntryIntegrationTest: @Transactional;
    
    @Autowired
    private FieldMappingValueMapEntryDataOnDemand FieldMappingValueMapEntryIntegrationTest.dod;
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testCountFieldMappingValueMapEntrys() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingValueMapEntry(), "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.countFieldMappingValueMapEntrys();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'FieldMappingValueMapEntry' incorrectly reported there were no entries");
    }
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testFindFieldMappingValueMapEntry() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry obj = dod.getRandomFieldMappingValueMapEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingValueMapEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.findFieldMappingValueMapEntry(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'FieldMappingValueMapEntry' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'FieldMappingValueMapEntry' returned the incorrect identifier");
    }
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testFindAllFieldMappingValueMapEntrys() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingValueMapEntry(), "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.countFieldMappingValueMapEntrys();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'FieldMappingValueMapEntry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.findAllFieldMappingValueMapEntrys();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'FieldMappingValueMapEntry' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'FieldMappingValueMapEntry' failed to return any data");
    }
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testFindFieldMappingValueMapEntryEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingValueMapEntry(), "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.countFieldMappingValueMapEntrys();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.findFieldMappingValueMapEntryEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'FieldMappingValueMapEntry' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'FieldMappingValueMapEntry' returned an incorrect number of entries");
    }
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry obj = dod.getRandomFieldMappingValueMapEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingValueMapEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.findFieldMappingValueMapEntry(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'FieldMappingValueMapEntry' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyFieldMappingValueMapEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'FieldMappingValueMapEntry' failed to increment on flush directive");
    }
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry obj = dod.getRandomFieldMappingValueMapEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingValueMapEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.findFieldMappingValueMapEntry(id);
        boolean modified =  dod.modifyFieldMappingValueMapEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry merged = (com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'FieldMappingValueMapEntry' failed to increment on merge and flush directive");
    }
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMappingValueMapEntry(), "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry obj = dod.getNewTransientFieldMappingValueMapEntry(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingValueMapEntry' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'FieldMappingValueMapEntry' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'FieldMappingValueMapEntry' identifier to no longer be null");
    }
    
    @Test
    public void FieldMappingValueMapEntryIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry obj = dod.getRandomFieldMappingValueMapEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMappingValueMapEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMappingValueMapEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.findFieldMappingValueMapEntry(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry.findFieldMappingValueMapEntry(id), "Failed to remove 'FieldMappingValueMapEntry' with identifier '" + id + "'");
    }
    
}
