// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect FieldMappingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldMappingIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: FieldMappingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FieldMappingIntegrationTest: @Transactional;
    
    @Autowired
    private FieldMappingDataOnDemand FieldMappingIntegrationTest.dod;
    
    @Test
    public void FieldMappingIntegrationTest.testCountFieldMappings() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMapping(), "Data on demand for 'FieldMapping' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.countFieldMappings();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'FieldMapping' incorrectly reported there were no entries");
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFindFieldMapping() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'FieldMapping' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'FieldMapping' returned the incorrect identifier");
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFindAllFieldMappings() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMapping(), "Data on demand for 'FieldMapping' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.countFieldMappings();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'FieldMapping', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMapping> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findAllFieldMappings();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'FieldMapping' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'FieldMapping' failed to return any data");
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFindFieldMappingEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMapping(), "Data on demand for 'FieldMapping' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.countFieldMappings();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.FieldMapping> result = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMappingEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'FieldMapping' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'FieldMapping' returned an incorrect number of entries");
    }
    
    @Test
    public void FieldMappingIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'FieldMapping' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyFieldMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'FieldMapping' failed to increment on flush directive");
    }
    
    @Test
    public void FieldMappingIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        boolean modified =  dod.modifyFieldMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping merged = (com.collabnet.ccf.ccfmaster.server.domain.FieldMapping) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'FieldMapping' failed to increment on merge and flush directive");
    }
    
    @Test
    public void FieldMappingIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomFieldMapping(), "Data on demand for 'FieldMapping' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getNewTransientFieldMapping(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMapping' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'FieldMapping' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'FieldMapping' identifier to no longer be null");
    }
    
    @Test
    public void FieldMappingIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.FieldMapping obj = dod.getRandomFieldMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'FieldMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'FieldMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.FieldMapping.findFieldMapping(id), "Failed to remove 'FieldMapping' with identifier '" + id + "'");
    }
    
}
