// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.HospitalEntryDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect HospitalEntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HospitalEntryIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: HospitalEntryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: HospitalEntryIntegrationTest: @Transactional;
    
    @Autowired
    private HospitalEntryDataOnDemand HospitalEntryIntegrationTest.dod;
    
    @Test
    public void HospitalEntryIntegrationTest.testCountHospitalEntrys() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomHospitalEntry(), "Data on demand for 'HospitalEntry' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.countHospitalEntrys();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'HospitalEntry' incorrectly reported there were no entries");
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFindHospitalEntry() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'HospitalEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'HospitalEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'HospitalEntry' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'HospitalEntry' returned the incorrect identifier");
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFindAllHospitalEntrys() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomHospitalEntry(), "Data on demand for 'HospitalEntry' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.countHospitalEntrys();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'HospitalEntry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry> result = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findAllHospitalEntrys();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'HospitalEntry' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'HospitalEntry' failed to return any data");
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFindHospitalEntryEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomHospitalEntry(), "Data on demand for 'HospitalEntry' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.countHospitalEntrys();
        if (20 < count) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry> result = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntryEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'HospitalEntry' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'HospitalEntry' returned an incorrect number of entries");
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'HospitalEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'HospitalEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'HospitalEntry' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyHospitalEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'HospitalEntry' failed to increment on flush directive");
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'HospitalEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'HospitalEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        boolean modified =  dod.modifyHospitalEntry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry merged = (com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'HospitalEntry' failed to increment on merge and flush directive");
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomHospitalEntry(), "Data on demand for 'HospitalEntry' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getNewTransientHospitalEntry(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'HospitalEntry' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'HospitalEntry' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'HospitalEntry' identifier to no longer be null");
    }
    
    @Test
    public void HospitalEntryIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry obj = dod.getRandomHospitalEntry();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'HospitalEntry' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'HospitalEntry' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry.findHospitalEntry(id), "Failed to remove 'HospitalEntry' with identifier '" + id + "'");
    }
    
}
