// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.LandscapeDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect LandscapeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LandscapeIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: LandscapeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LandscapeIntegrationTest: @Transactional;
    
    @Autowired
    private LandscapeDataOnDemand LandscapeIntegrationTest.dod;
    
    @Test
    public void LandscapeIntegrationTest.testCountLandscapes() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomLandscape(), "Data on demand for 'Landscape' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Landscape.countLandscapes();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'Landscape' incorrectly reported there were no entries");
    }
    
    @Test
    public void LandscapeIntegrationTest.testFindLandscape() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Landscape' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Landscape' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'Landscape' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'Landscape' returned the incorrect identifier");
    }
    
    @Test
    public void LandscapeIntegrationTest.testFindAllLandscapes() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomLandscape(), "Data on demand for 'Landscape' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Landscape.countLandscapes();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'Landscape', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Landscape> result = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findAllLandscapes();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'Landscape' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'Landscape' failed to return any data");
    }
    
    @Test
    public void LandscapeIntegrationTest.testFindLandscapeEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomLandscape(), "Data on demand for 'Landscape' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Landscape.countLandscapes();
        if (20 < count) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Landscape> result = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscapeEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'Landscape' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'Landscape' returned an incorrect number of entries");
    }
    
    @Test
    public void LandscapeIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Landscape' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Landscape' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'Landscape' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyLandscape(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'Landscape' failed to increment on flush directive");
    }
    
    @Test
    public void LandscapeIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Landscape' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Landscape' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        boolean modified =  dod.modifyLandscape(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.Landscape merged = (com.collabnet.ccf.ccfmaster.server.domain.Landscape) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'Landscape' failed to increment on merge and flush directive");
    }
    
    @Test
    public void LandscapeIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomLandscape(), "Data on demand for 'Landscape' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getNewTransientLandscape(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Landscape' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'Landscape' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'Landscape' identifier to no longer be null");
    }
    
    @Test
    public void LandscapeIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.Landscape obj = dod.getRandomLandscape();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Landscape' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Landscape' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.Landscape.findLandscape(id), "Failed to remove 'Landscape' with identifier '" + id + "'");
    }
    
}
