// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfigDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect ParticipantConfigIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticipantConfigIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: ParticipantConfigIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ParticipantConfigIntegrationTest: @Transactional;
    
    @Autowired
    private ParticipantConfigDataOnDemand ParticipantConfigIntegrationTest.dod;
    
    @Test
    public void ParticipantConfigIntegrationTest.testCountParticipantConfigs() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipantConfig(), "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.countParticipantConfigs();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'ParticipantConfig' incorrectly reported there were no entries");
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFindParticipantConfig() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ParticipantConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'ParticipantConfig' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'ParticipantConfig' returned the incorrect identifier");
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFindAllParticipantConfigs() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipantConfig(), "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.countParticipantConfigs();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'ParticipantConfig', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig> result = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findAllParticipantConfigs();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'ParticipantConfig' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'ParticipantConfig' failed to return any data");
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFindParticipantConfigEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipantConfig(), "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.countParticipantConfigs();
        if (20 < count) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig> result = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfigEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'ParticipantConfig' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'ParticipantConfig' returned an incorrect number of entries");
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ParticipantConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'ParticipantConfig' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyParticipantConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'ParticipantConfig' failed to increment on flush directive");
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ParticipantConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        boolean modified =  dod.modifyParticipantConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig merged = (com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'ParticipantConfig' failed to increment on merge and flush directive");
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipantConfig(), "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getNewTransientParticipantConfig(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ParticipantConfig' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'ParticipantConfig' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'ParticipantConfig' identifier to no longer be null");
    }
    
    @Test
    public void ParticipantConfigIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig obj = dod.getRandomParticipantConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'ParticipantConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'ParticipantConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.ParticipantConfig.findParticipantConfig(id), "Failed to remove 'ParticipantConfig' with identifier '" + id + "'");
    }
    
}
