// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.ParticipantDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect ParticipantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticipantIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: ParticipantIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ParticipantIntegrationTest: @Transactional;
    
    @Autowired
    private ParticipantDataOnDemand ParticipantIntegrationTest.dod;
    
    @Test
    public void ParticipantIntegrationTest.testCountParticipants() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipant(), "Data on demand for 'Participant' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Participant.countParticipants();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'Participant' incorrectly reported there were no entries");
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindParticipant() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Participant' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Participant' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'Participant' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'Participant' returned the incorrect identifier");
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindAllParticipants() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipant(), "Data on demand for 'Participant' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Participant.countParticipants();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'Participant', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Participant> result = com.collabnet.ccf.ccfmaster.server.domain.Participant.findAllParticipants();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'Participant' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'Participant' failed to return any data");
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindParticipantEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipant(), "Data on demand for 'Participant' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.Participant.countParticipants();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.Participant> result = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipantEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'Participant' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'Participant' returned an incorrect number of entries");
    }
    
    @Test
    public void ParticipantIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Participant' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Participant' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'Participant' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyParticipant(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'Participant' failed to increment on flush directive");
    }
    
    @Test
    public void ParticipantIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Participant' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Participant' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        boolean modified =  dod.modifyParticipant(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.Participant merged = (com.collabnet.ccf.ccfmaster.server.domain.Participant) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'Participant' failed to increment on merge and flush directive");
    }
    
    @Test
    public void ParticipantIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomParticipant(), "Data on demand for 'Participant' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getNewTransientParticipant(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Participant' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'Participant' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'Participant' identifier to no longer be null");
    }
    
    @Test
    public void ParticipantIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.Participant obj = dod.getRandomParticipant();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'Participant' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'Participant' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.Participant.findParticipant(id), "Failed to remove 'Participant' with identifier '" + id + "'");
    }
    
}
