// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfigDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect RepositoryMappingDirectionConfigIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepositoryMappingDirectionConfigIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: RepositoryMappingDirectionConfigIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RepositoryMappingDirectionConfigIntegrationTest: @Transactional;
    
    @Autowired
    private RepositoryMappingDirectionConfigDataOnDemand RepositoryMappingDirectionConfigIntegrationTest.dod;
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testCountRepositoryMappingDirectionConfigs() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMappingDirectionConfig(), "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.countRepositoryMappingDirectionConfigs();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'RepositoryMappingDirectionConfig' incorrectly reported there were no entries");
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFindRepositoryMappingDirectionConfig() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'RepositoryMappingDirectionConfig' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'RepositoryMappingDirectionConfig' returned the incorrect identifier");
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFindAllRepositoryMappingDirectionConfigs() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMappingDirectionConfig(), "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.countRepositoryMappingDirectionConfigs();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'RepositoryMappingDirectionConfig', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findAllRepositoryMappingDirectionConfigs();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'RepositoryMappingDirectionConfig' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'RepositoryMappingDirectionConfig' failed to return any data");
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFindRepositoryMappingDirectionConfigEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMappingDirectionConfig(), "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.countRepositoryMappingDirectionConfigs();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfigEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'RepositoryMappingDirectionConfig' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'RepositoryMappingDirectionConfig' returned an incorrect number of entries");
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'RepositoryMappingDirectionConfig' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyRepositoryMappingDirectionConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'RepositoryMappingDirectionConfig' failed to increment on flush directive");
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        boolean modified =  dod.modifyRepositoryMappingDirectionConfig(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig merged = (com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'RepositoryMappingDirectionConfig' failed to increment on merge and flush directive");
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMappingDirectionConfig(), "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getNewTransientRepositoryMappingDirectionConfig(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirectionConfig' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'RepositoryMappingDirectionConfig' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'RepositoryMappingDirectionConfig' identifier to no longer be null");
    }
    
    @Test
    public void RepositoryMappingDirectionConfigIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig obj = dod.getRandomRepositoryMappingDirectionConfig();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirectionConfig' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirectionConfig' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(id), "Failed to remove 'RepositoryMappingDirectionConfig' with identifier '" + id + "'");
    }
    
}