// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDataOnDemand;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect RepositoryMappingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepositoryMappingIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: RepositoryMappingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RepositoryMappingIntegrationTest: @Transactional;
    
    @Autowired
    private RepositoryMappingDataOnDemand RepositoryMappingIntegrationTest.dod;
    
    @Test
    public void RepositoryMappingIntegrationTest.testCountRepositoryMappings() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMapping(), "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.countRepositoryMappings();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'RepositoryMapping' incorrectly reported there were no entries");
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFindRepositoryMapping() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'RepositoryMapping' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'RepositoryMapping' returned the incorrect identifier");
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFindAllRepositoryMappings() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMapping(), "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.countRepositoryMappings();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'RepositoryMapping', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findAllRepositoryMappings();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'RepositoryMapping' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'RepositoryMapping' failed to return any data");
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFindRepositoryMappingEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMapping(), "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.countRepositoryMappings();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMappingEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'RepositoryMapping' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'RepositoryMapping' returned an incorrect number of entries");
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'RepositoryMapping' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyRepositoryMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'RepositoryMapping' failed to increment on flush directive");
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        boolean modified =  dod.modifyRepositoryMapping(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping merged = (com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'RepositoryMapping' failed to increment on merge and flush directive");
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testPersist() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMapping(), "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getNewTransientRepositoryMapping(Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMapping' failed to provide a new transient entity");
        org.junit.jupiter.api.Assertions.assertNull(obj.getId(), "Expected 'RepositoryMapping' identifier to be null");
        obj.persist();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNotNull(obj.getId(), "Expected 'RepositoryMapping' identifier to no longer be null");
    }
    
    @Test
    public void RepositoryMappingIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping obj = dod.getRandomRepositoryMapping();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMapping' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMapping' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.RepositoryMapping.findRepositoryMapping(id), "Failed to remove 'RepositoryMapping' with identifier '" + id + "'");
    }
    
}
