// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import org.junit.jupiter.api.Test;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;
import org.junit.jupiter.api.extension.ExtendWith;

privileged aspect RepositoryMappingDirectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepositoryMappingDirectionIntegrationTest: @ExtendWith(SpringExtension.class);
    
    declare @type: RepositoryMappingDirectionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RepositoryMappingDirectionIntegrationTest: @Transactional;
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testCountRepositoryMappingDirections() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMappingDirection(), "Data on demand for 'RepositoryMappingDirection' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.countRepositoryMappingDirections();
        org.junit.jupiter.api.Assertions.assertTrue(count > 0, "Counter for 'RepositoryMappingDirection' incorrectly reported there were no entries");
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFindRepositoryMappingDirection() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirection' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirection' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'RepositoryMappingDirection' illegally returned null for id '" + id + "'");
        org.junit.jupiter.api.Assertions.assertEquals(id, obj.getId(), "Find method for 'RepositoryMappingDirection' returned the incorrect identifier");
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFindAllRepositoryMappingDirections() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMappingDirection(), "Data on demand for 'RepositoryMappingDirection' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.countRepositoryMappingDirections();
        org.junit.jupiter.api.Assertions.assertTrue(count < 250, "Too expensive to perform a find all test for 'RepositoryMappingDirection', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test");
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findAllRepositoryMappingDirections();
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find all method for 'RepositoryMappingDirection' illegally returned null");
        org.junit.jupiter.api.Assertions.assertTrue(result.size() > 0, "Find all method for 'RepositoryMappingDirection' failed to return any data");
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFindRepositoryMappingDirectionEntries() {
        org.junit.jupiter.api.Assertions.assertNotNull(dod.getRandomRepositoryMappingDirection(), "Data on demand for 'RepositoryMappingDirection' failed to initialize correctly");
        long count = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.countRepositoryMappingDirections();
        if (count > 20) count = 20;
        java.util.List<com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection> result = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirectionEntries(0, (int) count);
        org.junit.jupiter.api.Assertions.assertNotNull(result, "Find entries method for 'RepositoryMappingDirection' illegally returned null");
        org.junit.jupiter.api.Assertions.assertEquals(count, result.size(), "Find entries method for 'RepositoryMappingDirection' returned an incorrect number of entries");
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testFlush() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirection' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirection' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Find method for 'RepositoryMappingDirection' illegally returned null for id '" + id + "'");
        boolean modified =  dod.modifyRepositoryMappingDirection(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'RepositoryMappingDirection' failed to increment on flush directive");
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testMerge() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirection' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirection' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        boolean modified =  dod.modifyRepositoryMappingDirection(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection merged = (com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection) obj.merge();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertEquals(merged.getId(), id, "Identifier of merged object not the same as identifier of original object");
        org.junit.jupiter.api.Assertions.assertTrue((currentVersion != null && obj.getVersion() > currentVersion) || !modified, "Version for 'RepositoryMappingDirection' failed to increment on merge and flush directive");
    }
    
    @Test
    public void RepositoryMappingDirectionIntegrationTest.testRemove() {
        com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection obj = dod.getRandomRepositoryMappingDirection();
        org.junit.jupiter.api.Assertions.assertNotNull(obj, "Data on demand for 'RepositoryMappingDirection' failed to initialize correctly");
        java.lang.Long id = obj.getId();
        org.junit.jupiter.api.Assertions.assertNotNull(id, "Data on demand for 'RepositoryMappingDirection' failed to provide an identifier");
        obj = com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id);
        obj.remove();
        obj.flush();
        org.junit.jupiter.api.Assertions.assertNull(com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection.findRepositoryMappingDirection(id), "Failed to remove 'RepositoryMappingDirection' with identifier '" + id + "'");
    }
    
}
