// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingRule;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldMappingRule_Roo_Entity {
    
    declare @type: FieldMappingRule: @Entity;
    
    @PersistenceContext
    transient EntityManager FieldMappingRule.entityManager;
    
    @Id
    // GenerationType.AUTO used to mean "native", i.e. an HSQLDB identity
    // column, because Hibernate 3.5 defaulted hibernate.id.new_generator_mappings
    // to false. Hibernate 6 always reads AUTO as a sequence, which both changes the
    // schema and defers the INSERT from persist() to flush() - two integration tests
    // rely on the constraint violation surfacing from persist(). IDENTITY is the
    // baseline mapping, spelled out.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long FieldMappingRule.id;
    
    @Version
    @Column(name = "version")
    private Integer FieldMappingRule.version;
    
    public Long FieldMappingRule.getId() {
        return this.id;
    }
    
    public void FieldMappingRule.setId(Long id) {
        this.id = id;
    }
    
    public Integer FieldMappingRule.getVersion() {
        return this.version;
    }
    
    public void FieldMappingRule.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void FieldMappingRule.persist() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void FieldMappingRule.remove() {
        if (null == this.entityManager) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            FieldMappingRule attached = FieldMappingRule.findFieldMappingRule(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void FieldMappingRule.flush() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void FieldMappingRule.clear() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public FieldMappingRule FieldMappingRule.merge() {
        if (null == this.entityManager) this.entityManager = entityManager();
        FieldMappingRule merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager FieldMappingRule.entityManager() {
        EntityManager em = new FieldMappingRule().entityManager;
        if (null == em) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long FieldMappingRule.countFieldMappingRules() {
        return entityManager().createQuery("SELECT COUNT(o) FROM FieldMappingRule o", Long.class).getSingleResult();
    }
    
    public static List<FieldMappingRule> FieldMappingRule.findAllFieldMappingRules() {
        return entityManager().createQuery("SELECT o FROM FieldMappingRule o", FieldMappingRule.class).getResultList();
    }
    
    public static FieldMappingRule FieldMappingRule.findFieldMappingRule(Long id) {
        if (null == id) return null;
        return entityManager().find(FieldMappingRule.class, id);
    }
    
    public static List<FieldMappingRule> FieldMappingRule.findFieldMappingRuleEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM FieldMappingRule o", FieldMappingRule.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
