// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingExternalAppTemplate;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldMappingExternalAppTemplate_Roo_Entity {
    
    declare @type: FieldMappingExternalAppTemplate: @Entity;
    
    @PersistenceContext
    transient EntityManager FieldMappingExternalAppTemplate.entityManager;
    
    @Id
    // GenerationType.AUTO used to mean "native", i.e. an HSQLDB identity
    // column, because Hibernate 3.5 defaulted hibernate.id.new_generator_mappings
    // to false. Hibernate 6 always reads AUTO as a sequence, which both changes the
    // schema and defers the INSERT from persist() to flush() - two integration tests
    // rely on the constraint violation surfacing from persist(). IDENTITY is the
    // baseline mapping, spelled out.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long FieldMappingExternalAppTemplate.id;
    
    @Version
    @Column(name = "version")
    private Integer FieldMappingExternalAppTemplate.version;
    
    public Long FieldMappingExternalAppTemplate.getId() {
        return this.id;
    }
    
    public void FieldMappingExternalAppTemplate.setId(Long id) {
        this.id = id;
    }
    
    public Integer FieldMappingExternalAppTemplate.getVersion() {
        return this.version;
    }
    
    public void FieldMappingExternalAppTemplate.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void FieldMappingExternalAppTemplate.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void FieldMappingExternalAppTemplate.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            FieldMappingExternalAppTemplate attached = FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplate(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void FieldMappingExternalAppTemplate.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void FieldMappingExternalAppTemplate.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public FieldMappingExternalAppTemplate FieldMappingExternalAppTemplate.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        FieldMappingExternalAppTemplate merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager FieldMappingExternalAppTemplate.entityManager() {
        EntityManager em = new FieldMappingExternalAppTemplate().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long FieldMappingExternalAppTemplate.countFieldMappingExternalAppTemplates() {
        return entityManager().createQuery("SELECT COUNT(o) FROM FieldMappingExternalAppTemplate o", Long.class).getSingleResult();
    }
    
    public static List<FieldMappingExternalAppTemplate> FieldMappingExternalAppTemplate.findAllFieldMappingExternalAppTemplates() {
        return entityManager().createQuery("SELECT o FROM FieldMappingExternalAppTemplate o", FieldMappingExternalAppTemplate.class).getResultList();
    }
    
    public static FieldMappingExternalAppTemplate FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplate(Long id) {
        if (id == null) return null;
        return entityManager().find(FieldMappingExternalAppTemplate.class, id);
    }
    
    public static List<FieldMappingExternalAppTemplate> FieldMappingExternalAppTemplate.findFieldMappingExternalAppTemplateEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM FieldMappingExternalAppTemplate o", FieldMappingExternalAppTemplate.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
