// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.FieldMappingValueMapEntry;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldMappingValueMapEntry_Roo_Entity {
    
    declare @type: FieldMappingValueMapEntry: @Entity;
    
    @PersistenceContext
    transient EntityManager FieldMappingValueMapEntry.entityManager;
    
    @Id
    // GenerationType.AUTO used to mean "native", i.e. an HSQLDB identity
    // column, because Hibernate 3.5 defaulted hibernate.id.new_generator_mappings
    // to false. Hibernate 6 always reads AUTO as a sequence, which both changes the
    // schema and defers the INSERT from persist() to flush() - two integration tests
    // rely on the constraint violation surfacing from persist(). IDENTITY is the
    // baseline mapping, spelled out.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long FieldMappingValueMapEntry.id;
    
    @Version
    @Column(name = "version")
    private Integer FieldMappingValueMapEntry.version;
    
    public Long FieldMappingValueMapEntry.getId() {
        return this.id;
    }
    
    public void FieldMappingValueMapEntry.setId(Long id) {
        this.id = id;
    }
    
    public Integer FieldMappingValueMapEntry.getVersion() {
        return this.version;
    }
    
    public void FieldMappingValueMapEntry.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void FieldMappingValueMapEntry.persist() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void FieldMappingValueMapEntry.remove() {
        if (null == this.entityManager) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            FieldMappingValueMapEntry attached = FieldMappingValueMapEntry.findFieldMappingValueMapEntry(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void FieldMappingValueMapEntry.flush() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void FieldMappingValueMapEntry.clear() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public FieldMappingValueMapEntry FieldMappingValueMapEntry.merge() {
        if (null == this.entityManager) this.entityManager = entityManager();
        FieldMappingValueMapEntry merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager FieldMappingValueMapEntry.entityManager() {
        EntityManager em = new FieldMappingValueMapEntry().entityManager;
        if (null == em) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long FieldMappingValueMapEntry.countFieldMappingValueMapEntrys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM FieldMappingValueMapEntry o", Long.class).getSingleResult();
    }
    
    public static List<FieldMappingValueMapEntry> FieldMappingValueMapEntry.findAllFieldMappingValueMapEntrys() {
        return entityManager().createQuery("SELECT o FROM FieldMappingValueMapEntry o", FieldMappingValueMapEntry.class).getResultList();
    }
    
    public static FieldMappingValueMapEntry FieldMappingValueMapEntry.findFieldMappingValueMapEntry(Long id) {
        if (null == id) return null;
        return entityManager().find(FieldMappingValueMapEntry.class, id);
    }
    
    public static List<FieldMappingValueMapEntry> FieldMappingValueMapEntry.findFieldMappingValueMapEntryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM FieldMappingValueMapEntry o", FieldMappingValueMapEntry.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
