// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.HospitalEntry;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HospitalEntry_Roo_Entity {
    
    declare @type: HospitalEntry: @Entity;
    
    @PersistenceContext
    transient EntityManager HospitalEntry.entityManager;
    
    @Id
    // GenerationType.AUTO used to mean "native", i.e. an HSQLDB identity
    // column, because Hibernate 3.5 defaulted hibernate.id.new_generator_mappings
    // to false. Hibernate 6 always reads AUTO as a sequence, which both changes the
    // schema and defers the INSERT from persist() to flush() - two integration tests
    // rely on the constraint violation surfacing from persist(). IDENTITY is the
    // baseline mapping, spelled out.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long HospitalEntry.id;
    
    @Version
    @Column(name = "version")
    private Integer HospitalEntry.version;
    
    public Long HospitalEntry.getId() {
        return this.id;
    }
    
    public void HospitalEntry.setId(Long id) {
        this.id = id;
    }
    
    public Integer HospitalEntry.getVersion() {
        return this.version;
    }
    
    public void HospitalEntry.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void HospitalEntry.persist() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void HospitalEntry.remove() {
        if (null == this.entityManager) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            HospitalEntry attached = HospitalEntry.findHospitalEntry(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void HospitalEntry.flush() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void HospitalEntry.clear() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public HospitalEntry HospitalEntry.merge() {
        if (null == this.entityManager) this.entityManager = entityManager();
        HospitalEntry merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager HospitalEntry.entityManager() {
        EntityManager em = new HospitalEntry().entityManager;
        if (null == em) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long HospitalEntry.countHospitalEntrys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM HospitalEntry o", Long.class).getSingleResult();
    }
    
    public static List<HospitalEntry> HospitalEntry.findAllHospitalEntrys() {
        return entityManager().createQuery("SELECT o FROM HospitalEntry o", HospitalEntry.class).getResultList();
    }
    
    public static HospitalEntry HospitalEntry.findHospitalEntry(Long id) {
        if (null == id) return null;
        return entityManager().find(HospitalEntry.class, id);
    }
    
    public static List<HospitalEntry> HospitalEntry.findHospitalEntryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM HospitalEntry o", HospitalEntry.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
