// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.IdentityMapping;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IdentityMapping_Roo_Entity {
    
    declare @type: IdentityMapping: @Entity;
    
    @PersistenceContext
    transient EntityManager IdentityMapping.entityManager;
    
    @Id
    // GenerationType.AUTO used to mean "native", i.e. an HSQLDB identity
    // column, because Hibernate 3.5 defaulted hibernate.id.new_generator_mappings
    // to false. Hibernate 6 always reads AUTO as a sequence, which both changes the
    // schema and defers the INSERT from persist() to flush() - two integration tests
    // rely on the constraint violation surfacing from persist(). IDENTITY is the
    // baseline mapping, spelled out.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long IdentityMapping.id;
    
    @Version
    @Column(name = "version")
    private Integer IdentityMapping.version;
    
    public Long IdentityMapping.getId() {
        return this.id;
    }
    
    public void IdentityMapping.setId(Long id) {
        this.id = id;
    }
    
    public Integer IdentityMapping.getVersion() {
        return this.version;
    }
    
    public void IdentityMapping.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void IdentityMapping.persist() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void IdentityMapping.remove() {
        if (null == this.entityManager) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            IdentityMapping attached = IdentityMapping.findIdentityMapping(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void IdentityMapping.flush() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void IdentityMapping.clear() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public IdentityMapping IdentityMapping.merge() {
        if (null == this.entityManager) this.entityManager = entityManager();
        IdentityMapping merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager IdentityMapping.entityManager() {
        EntityManager em = new IdentityMapping().entityManager;
        if (null == em) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long IdentityMapping.countIdentityMappings() {
        return entityManager().createQuery("SELECT COUNT(o) FROM IdentityMapping o", Long.class).getSingleResult();
    }
    
    public static List<IdentityMapping> IdentityMapping.findAllIdentityMappings() {
        return entityManager().createQuery("SELECT o FROM IdentityMapping o", IdentityMapping.class).getResultList();
    }
    
    public static IdentityMapping IdentityMapping.findIdentityMapping(Long id) {
        if (null == id) return null;
        return entityManager().find(IdentityMapping.class, id);
    }
    
    public static List<IdentityMapping> IdentityMapping.findIdentityMappingEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM IdentityMapping o", IdentityMapping.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
