// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.Landscape;
import com.collabnet.ccf.ccfmaster.server.domain.LandscapeConfig;
import java.lang.String;
import jakarta.persistence.EntityManager;
import jakarta.persistence.TypedQuery;

privileged aspect LandscapeConfig_Roo_Finder {
    
    public static TypedQuery<LandscapeConfig> LandscapeConfig.findLandscapeConfigsByLandscape(Landscape landscape) {
        if (null == landscape) throw new IllegalArgumentException("The landscape argument is required");
        EntityManager em = LandscapeConfig.entityManager();
        TypedQuery<LandscapeConfig> q = em.createQuery("SELECT o FROM LandscapeConfig AS o WHERE o.landscape = :landscape", LandscapeConfig.class);
        q.setParameter("landscape", landscape);
        return q;
    }
    
    public static TypedQuery<LandscapeConfig> LandscapeConfig.findLandscapeConfigsByLandscapeAndName(Landscape landscape, String name) {
        if (null == landscape) throw new IllegalArgumentException("The landscape argument is required");
        if (null == name || 0 == name.length()) throw new IllegalArgumentException("The name argument is required");
        EntityManager em = LandscapeConfig.entityManager();
        TypedQuery<LandscapeConfig> q = em.createQuery("SELECT o FROM LandscapeConfig AS o WHERE o.landscape = :landscape AND o.name = :name", LandscapeConfig.class);
        q.setParameter("landscape", landscape);
        q.setParameter("name", name);
        return q;
    }
    
}
