// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.Landscape;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Landscape_Roo_Entity {
    
    declare @type: Landscape: @Entity;
    
    @PersistenceContext
    transient EntityManager Landscape.entityManager;
    
    @Id
    // GenerationType.AUTO used to mean "native", i.e. an HSQLDB identity
    // column, because Hibernate 3.5 defaulted hibernate.id.new_generator_mappings
    // to false. Hibernate 6 always reads AUTO as a sequence, which both changes the
    // schema and defers the INSERT from persist() to flush() - two integration tests
    // rely on the constraint violation surfacing from persist(). IDENTITY is the
    // baseline mapping, spelled out.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long Landscape.id;
    
    @Version
    @Column(name = "version")
    private Integer Landscape.version;
    
    public Long Landscape.getId() {
        return this.id;
    }
    
    public void Landscape.setId(Long id) {
        this.id = id;
    }
    
    public Integer Landscape.getVersion() {
        return this.version;
    }
    
    public void Landscape.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void Landscape.persist() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Landscape.remove() {
        if (null == this.entityManager) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Landscape attached = Landscape.findLandscape(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Landscape.flush() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Landscape.clear() {
        if (null == this.entityManager) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Landscape Landscape.merge() {
        if (null == this.entityManager) this.entityManager = entityManager();
        Landscape merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Landscape.entityManager() {
        EntityManager em = new Landscape().entityManager;
        if (null == em) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Landscape.countLandscapes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Landscape o", Long.class).getSingleResult();
    }
    
    public static List<Landscape> Landscape.findAllLandscapes() {
        return entityManager().createQuery("SELECT o FROM Landscape o", Landscape.class).getResultList();
    }
    
    public static Landscape Landscape.findLandscape(Long id) {
        if (null == id) return null;
        return entityManager().find(Landscape.class, id);
    }
    
    public static List<Landscape> Landscape.findLandscapeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Landscape o", Landscape.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
