// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.Landscape;
import java.lang.String;
import jakarta.persistence.EntityManager;
import jakarta.persistence.TypedQuery;

privileged aspect Landscape_Roo_Finder {
    
    public static TypedQuery<Landscape> Landscape.findLandscapesByPlugIdEquals(String plugId) {
        if (null == plugId || 0 == plugId.length()) throw new IllegalArgumentException("The plugId argument is required");
        EntityManager em = Landscape.entityManager();
        TypedQuery<Landscape> q = em.createQuery("SELECT o FROM Landscape AS o WHERE o.plugId = :plugId", Landscape.class);
        q.setParameter("plugId", plugId);
        return q;
    }
    
}
