// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirection;
import com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig;
import jakarta.persistence.EntityManager;
import jakarta.persistence.TypedQuery;

privileged aspect RepositoryMappingDirectionConfig_Roo_Finder {
    
    public static TypedQuery<RepositoryMappingDirectionConfig> RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfigsByRepositoryMappingDirection(RepositoryMappingDirection repositoryMappingDirection) {
        if (null == repositoryMappingDirection) throw new IllegalArgumentException("The repositoryMappingDirection argument is required");
        EntityManager em = RepositoryMappingDirectionConfig.entityManager();
        TypedQuery<RepositoryMappingDirectionConfig> q = em.createQuery("SELECT o FROM RepositoryMappingDirectionConfig AS o WHERE o.repositoryMappingDirection = :repositoryMappingDirection", RepositoryMappingDirectionConfig.class);
        q.setParameter("repositoryMappingDirection", repositoryMappingDirection);
        return q;
    }
    
}
