// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.collabnet.ccf.ccfmaster.server.domain;

import com.collabnet.ccf.ccfmaster.server.domain.RepositoryMappingDirectionConfig;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RepositoryMappingDirectionConfig_Roo_Entity {
    
    declare @type: RepositoryMappingDirectionConfig: @Entity;
    
    @PersistenceContext
    transient EntityManager RepositoryMappingDirectionConfig.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long RepositoryMappingDirectionConfig.id;
    
    @Version
    @Column(name = "version")
    private Integer RepositoryMappingDirectionConfig.version;
    
    public Long RepositoryMappingDirectionConfig.getId() {
        return this.id;
    }
    
    public void RepositoryMappingDirectionConfig.setId(Long id) {
        this.id = id;
    }
    
    public Integer RepositoryMappingDirectionConfig.getVersion() {
        return this.version;
    }
    
    public void RepositoryMappingDirectionConfig.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void RepositoryMappingDirectionConfig.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void RepositoryMappingDirectionConfig.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            RepositoryMappingDirectionConfig attached = RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void RepositoryMappingDirectionConfig.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void RepositoryMappingDirectionConfig.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public RepositoryMappingDirectionConfig RepositoryMappingDirectionConfig.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        RepositoryMappingDirectionConfig merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager RepositoryMappingDirectionConfig.entityManager() {
        EntityManager em = new RepositoryMappingDirectionConfig().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long RepositoryMappingDirectionConfig.countRepositoryMappingDirectionConfigs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM RepositoryMappingDirectionConfig o", Long.class).getSingleResult();
    }
    
    public static List<RepositoryMappingDirectionConfig> RepositoryMappingDirectionConfig.findAllRepositoryMappingDirectionConfigs() {
        return entityManager().createQuery("SELECT o FROM RepositoryMappingDirectionConfig o", RepositoryMappingDirectionConfig.class).getResultList();
    }
    
    public static RepositoryMappingDirectionConfig RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfig(Long id) {
        if (id == null) return null;
        return entityManager().find(RepositoryMappingDirectionConfig.class, id);
    }
    
    public static List<RepositoryMappingDirectionConfig> RepositoryMappingDirectionConfig.findRepositoryMappingDirectionConfigEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM RepositoryMappingDirectionConfig o", RepositoryMappingDirectionConfig.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
